name: dart_tutorial
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.5 <3.0.0'

# dependencies:
#   path: ^1.8.0

dependencies:
  beautiful_soup_dart: ^0.3.0
  http: ^1.1.2
  lints: ^3.0.0
  test: ^1.24.9
  webdriver: ^3.0.3
